version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest  # Use an appropriate image
    steps:
      - checkout  # Clone the repository
      - run:
          name: Show Git Status
          command: git status
      - run:
          name: Run Basic Tests
          command: echo "Running tests..." && exit 0

workflows:
  version: 2
  basic-workflow:
    jobs:
      - build
